### ISSUE TITLE
Plugin not working in Mint 20.1?

### ISSUE THREAD

**Issue by uditarenos** [gerardsimons/recoll-albert#1]
Hey!
First of all, thank you very much for the work!
Unfortunately, I cannot get the plugin to work, because i cannot activate it in Albert.
I'm on Linux Mint 20.1 which has Ubuntu 20.04 as its base. 

Albert Launcher  0.17.2
recoll: 1.26.3
libxapian30: 1.4.14-2

See screenshot. There is a "x" next to albert-recoll
![Bildschirmfoto vom 2021-03-10 22-04-43](https://user-images.githubusercontent.com/77104533/110697471-b2628c80-81ec-11eb-8dbc-43a9012035e1.png)

**Comment by gerardsimons** [comment]
Hey! Cool that you tried it, too bad it doesn't work. I haven't tried it myself for a while to be honest, as I went back to Mac .. It looks like there's more stuff grayed out though, not sure if that has something to do with it? Can you check the logs of albert to see what's going on?

**Comment by uditarenos** [comment]
Hi! Oh what a pity, that you went back to Mac! ;-)
All the more: thanks for your answer! I followed your hint and started Albert on a terminal. The output gave me:

`[warn:python.modulev1] [recoll_albert] Module has no __title__ specified`

So I edited the `__init__.py` file and added the line:
`__title__ = "Recoll"`

I restarted Albert and Recoll was correctly loaded, so that I could activate it.

Then the terminal gives me this:
`[warn:python.modulev1] [recoll_albert] ModuleNotFoundError: No module named 'albertv0'`

`At:`
`  ~/.local/share/albert/org.albert.extension.python/modules/recoll_albert/__init__.py(13): <module>
  <frozen importlib._bootstrap>(219): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(783): exec_module`

Is this just a simple name problem? If this is easily fixable, I would be grateful to hear your input. If this is a matter of extensive coding, I assume this is probably not worth the investment, since there will be other unanticipated problems as well.

I'd be glad to hear your assessment.

**Comment by gerardsimons** [comment]
Nice job on the __title__ for __init__.py. We can at least add that to the code if you make a pull request. But let's try to fix the rest first

 it just looks like it didn't install the Albert Python package? What's your `pip freeze` and also `python --version`

**Comment by uditarenos** [comment]
My python version is: 3.8.5

Python3-pip is not installed on my system. Do i need that?

**Comment by gerardsimons** [comment]
Looking back at the README, I had an issue with Python 3.8 and up. I would recommend 3.7. Nevertheless this error does seem to indicate a different problem, one in which the Python extension package of Albert itself is not found. Did you take a look at this page? https://github.com/albertlauncher/plugins/blob/master/python/README.md

**Comment by uditarenos** [comment]
I read through the site you posted, but couldn't find anything that would help me here.

I tested several changes on the `__init__.py` file, but nothing changed the error, unfortunately. 

I guess this is where I am at my wit's end. I will probably just use recoll as a standalone app.

Thank you for very much, though!

**Comment by gerardsimons** [comment]
Hmmmm, yes sorry if I couldn't help you more ... But as I mentioned before I think your Albert Python plug-in is not installed properly. That's why it says so about the albertv0 module. You can verify both recoll and Albert python installation by running

`python -c "import recoll; import albertv0"`

**Comment by uditarenos** [comment]
Hmm, it tells me 
`ModuleNotFoundError: No module named 'albertv0' `

**Comment by gerardsimons** [comment]
Yeah so the problem is not the plugin, it's your Albert installation, in particular the Python extensions library. The plug-in needs the Python package to communicate with Albert. Have you tried asking on the Telegram or Discord channels?

**Comment by uditarenos** [comment]
Oh! That hint brought me test the following: 
I changed `albertv0` to `albert`. And that's it! Module can be loaded ;-)
But then i tested the extension first without and then with the 'rc' trigger. But it doesn't seem to work.
But I can't see any error code.

**Comment by gerardsimons** [comment]
Glad you fixed it! Did you try to use the same request in recoll itself with `recoll -t <query>` ?

**Comment by gerardsimons** [comment]
It's also useful to run albert from terminal and see what it prints when you issue commands like these, please post them here

**Comment by uditarenos** [comment]
Hey! Thanks for the comments!

`recoll -t <query>` does work. I tested in a terminal.

I started albert via terminal and at first, I only got this error:
`[debg:calculator] Muparser SetExpr exception:  Unexpected token "rc " found at position 0.`

I had the trigger line uncommented. So I commented out the trigger line again.

Then I get this error code:
```

13:06:42 [debg:core] ========== QUERY: brunner  ==========
13:06:42 [debg:core] TIME:    131 µs SESSION TEARDOWN OVERALL
13:06:42 [debg:core] TIME:      0 µs MATCHES [org.albert.extension.terminal]
13:06:42 [debg:core] TIME:    103 µs MATCHES [org.albert.extension.applications]
13:06:42 [debg:core] TIME:      3 µs MATCHES [org.albert]
13:06:42 [debg:core] TIME:    124 µs MATCHES [org.albert.extension.websearch]
13:06:42 [debg:calculator] Muparser SetExpr exception:  Unexpected token "brunner" found at position 0.
13:06:42 [debg:core] TIME:    242 µs MATCHES [org.albert.extension.calculator]
13:06:42 [debg:core] TIME:    302 µs MATCHES [org.albert.extension.files]
13:06:42 [debg:core] TIME:   1290 µs MATCHES [org.albert.extension.firefoxbookmarks]
:3:common/rclinit.cpp:353::Recoll 1.26.3 + Xapian 1.4.14 [~/.recoll]
Traceback (most recent call last):
  File "~/.local/share/albert/org.albert.extension.python/modules/recoll_albert/__init__.py", line 182, in handleQuery
    results = recoll_docs_as_items(docs)
  File "~/.local/share/albert/org.albert.extension.python/modules/recoll_albert/__init__.py", line 148, in recoll_docs_as_items
    v0.TermAction(text=OPEN_TERMINAL_AT_THIS_PATH, commandline=[""],
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. albert.TermAction(text: QString, commandline: QStringList, cwd: QString = '')
    2. albert.TermAction(text: QString, script: QString, behavior: albert.TermAction.CloseBehavior = <CloseBehavior.CloseOnSuccess: 0>, cwd: QString = '')

Invoked with: kwargs: text='Open terminal at this path', commandline=[''], behavior=<CloseBehavior.DoNotClose: 2>, cwd='~/Lesen'

13:06:42 [warn:python.modulev1] [recoll_albert] TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. albert.TermAction(text: QString, commandline: QStringList, cwd: QString = '')
    2. albert.TermAction(text: QString, script: QString, behavior: albert.TermAction.CloseBehavior = <CloseBehavior.CloseOnSuccess: 0>, cwd: QString = '')

Invoked with: kwargs: text='Open terminal at this path', commandline=[''], behavior=<CloseBehavior.DoNotClose: 2>, cwd='~/Lesen'

At:
  ~/.local/share/albert/org.albert.extension.python/modules/recoll_albert/__init__.py(148): recoll_docs_as_items
  ~/.local/share/albert/org.albert.extension.python/modules/recoll_albert/__init__.py(186): handleQuery
.
13:06:42 [debg:core] TIME:   7670 µs MATCHES [org.albert.extension.python]
13:06:42 [debg:core] TIME:   8840 µs QUERY OVERALL
```

**Comment by gerardsimons** [comment]
Hey I think it's because I need to upgrade it to the latest albert (hence the dropping of the v0 suffix). I actually have another Linux computer so I will try it soon!

**Comment by hemanti0503** [comment]
Hey, just to let you know that I'm having the same problem as the OT. I'm glad it's getting solved. :)

**Comment by gerardsimons** [comment]
Yep! Sorry for the delay, I will be taking a look at this next week!

**Comment by gerardsimons** [comment]
Still working on this: Not quite such an easy fix as I had initially thought. I think it easier to just start from scratch from a new V1 example of Albert Python extension. Keep you posted ...

**Comment by wechsler42** [comment]
Hi there,
I tried to get the plugin working on Cinnamon 5.2 but unfortunately I failed with the same error report as @uditarenos posted here. So Gerard any chance that you will overhaul the plugin?

**Comment by gerardsimons** [comment]
Sorry I do not have a Linux PC anymore so it's a little hard to develop for me right now ...
